# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and ts config
COPY package*.json ./
COPY tsconfig.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy source files
COPY src ./src

# Build the project
RUN npm run build

# Expose a port if necessary (MCP typically uses stdio; adjust if needed)

# Set the CMD to run the MCP server
CMD [ "node", "build/index.js" ]
